@startgantt

'Section to start listing tasks

!$projason = %load_json(tasks.json)

!if %json_key_exists($projason, startDate)
    project starts $projason.startDate
!endif

!if %json_key_exists($projason, closedDays)
    !foreach $day in $projason.closedDays
        !if %json_key_exists($day, day)
            $day.day are closed
        !endif
        !if %json_key_exists($day, date)
            $day.date is closed
        !endif
    !endfor
!endif


!foreach $ta in $projason.tasks
    !if ($ta.id > 0)
        !$strvar = ""
        !if %json_key_exists($ta, resources)
            !$strvar = $strvar + "on "
            !foreach $re in $ta.resources
                !$strvar = $strvar + "{"
                !$strvar = $strvar + $re.name:$re.percent%
                !$strvar = $strvar + "}"
            !endfor
        !endif
        [$ta.description] $strvar requires $ta.duration days
    !endif
!endfor

'add starting constraint
!foreach $ta in $projason.tasks
    !if %json_key_exists($ta, starts)
        [$ta.description] starts %string($ta.starts)
    !endif
!endfor

'section to add in precedding tasks

!foreach $ts in $projason.tasks
    !if (%json_key_exists($ts, predecessors))
        !if (%get_json_type($ts.predecessors) == "array")
            !foreach $pr in $ts.predecessors
                !foreach $tf in $projason.tasks
                    !if ($pr == $tf.id)
                        [$tf.description] -> [$ts.description]
                    !endif
                !endfor
            !endfor
        !else !if (%get_json_type($ts.predecessors) == "number")
            !foreach $tf2 in $projason.tasks
                !if ($ts.predecessors == $tf2.id)
                    [$tf2.description] -> [$ts.description]
                !endif
            !endfor
        !endif
    !endif
!endfor

'task completeion listings
!foreach $task in $projason.tasks
    !if %json_key_exists($task, completed)
        [$task.description] is $task.completed completed
    !else
        [$task.description] is 0 completed
    !endif
!endfor

!if %json_key_exists($projason, projectName)
title $projason.projectName
!endif

footer Made by PUML Strungs: Gantt

@endgantt
